// manage student
export const SAVE_SET_LIST_STUDENT = "SAVE_SET_LIST_STUDENT";
export const SAVE_SET_SELECTED_STUDENT = "SAVE_SET_SELECTED_STUDENT";
export const SAVE_CREATE_STUDENT = "SAVE_CREATE_STUDENT";
export const SAVE_UPDATE_STUDENT = "SAVE_UPDATE_STUDENT";
export const SAVE_DELETE_STUDENT = "SAVE_DELETE_STUDENT";
export const SET_MODAL_STUDENT_VISIBLE = "SET_MODAL_STUDENT_VISIBLE";
export const ADD_STUDENT_CV_MODAL = "ADD_STUDENT_CV_MODAL";
export const SAVE_ADD_CV = "SAVE_ADD_CV";
export const ACT_SELECTED_ADD = "ACT_SELECTED_ADD";
export const CHOOSE_DATE_CV = "CHOOSE_DATE_CV";
export const DATE_CREATE_CV = "DATE_CREATE_CV";

export const SAVE_LIST_POST = "SAVE_LIST_POST";
